import { UniverseAsset } from "@/lib/types";

export const investmentUniverse: UniverseAsset[] = [
  {
    id: "stock-reliance",
    provider: "yahoo",
    category: "equity",
    marketSymbol: "RELIANCE.NS",
    benchmarkSymbol: "^NSEI",
    nameHint: "Reliance Industries",
    fundHouse: "NSE",
    expenseRatio: 0.05,
    aumCr: 250000,
    trackingError: 0.18,
    managerTenureYears: 12,
    downsideCaptureRatio: 96
  },
  {
    id: "stock-tcs",
    provider: "yahoo",
    category: "equity",
    marketSymbol: "TCS.NS",
    benchmarkSymbol: "^NSEI",
    nameHint: "Tata Consultancy Services",
    fundHouse: "NSE",
    expenseRatio: 0.05,
    aumCr: 180000,
    trackingError: 0.2,
    managerTenureYears: 10,
    downsideCaptureRatio: 94
  },
  {
    id: "stock-infy",
    provider: "yahoo",
    category: "equity",
    marketSymbol: "INFY.NS",
    benchmarkSymbol: "^NSEI",
    nameHint: "Infosys",
    fundHouse: "NSE",
    expenseRatio: 0.05,
    aumCr: 140000,
    trackingError: 0.19,
    managerTenureYears: 11,
    downsideCaptureRatio: 93
  },
  {
    id: "stock-hdfcbank",
    provider: "yahoo",
    category: "equity",
    marketSymbol: "HDFCBANK.NS",
    benchmarkSymbol: "^NSEI",
    nameHint: "HDFC Bank",
    fundHouse: "NSE",
    expenseRatio: 0.05,
    aumCr: 210000,
    trackingError: 0.22,
    managerTenureYears: 9,
    downsideCaptureRatio: 91
  },
  {
    id: "stock-icicibank",
    provider: "yahoo",
    category: "equity",
    marketSymbol: "ICICIBANK.NS",
    benchmarkSymbol: "^NSEI",
    nameHint: "ICICI Bank",
    fundHouse: "NSE",
    expenseRatio: 0.05,
    aumCr: 175000,
    trackingError: 0.21,
    managerTenureYears: 9,
    downsideCaptureRatio: 92
  },
  {
    id: "stock-hindunilvr",
    provider: "yahoo",
    category: "equity",
    marketSymbol: "HINDUNILVR.NS",
    benchmarkSymbol: "^NSEI",
    nameHint: "Hindustan Unilever",
    fundHouse: "NSE",
    expenseRatio: 0.05,
    aumCr: 95000,
    trackingError: 0.17,
    managerTenureYears: 8,
    downsideCaptureRatio: 88
  },
  {
    id: "stock-lt",
    provider: "yahoo",
    category: "equity",
    marketSymbol: "LT.NS",
    benchmarkSymbol: "^NSEI",
    nameHint: "Larsen & Toubro",
    fundHouse: "NSE",
    expenseRatio: 0.05,
    aumCr: 90000,
    trackingError: 0.23,
    managerTenureYears: 8,
    downsideCaptureRatio: 97
  },
  {
    id: "stock-bhartiartl",
    provider: "yahoo",
    category: "equity",
    marketSymbol: "BHARTIARTL.NS",
    benchmarkSymbol: "^NSEI",
    nameHint: "Bharti Airtel",
    fundHouse: "NSE",
    expenseRatio: 0.05,
    aumCr: 88000,
    trackingError: 0.24,
    managerTenureYears: 7,
    downsideCaptureRatio: 95
  },
  {
    id: "etf-niftybees",
    provider: "yahoo",
    category: "equity",
    marketSymbol: "NIFTYBEES.NS",
    benchmarkSymbol: "^NSEI",
    nameHint: "NIFTYBEES ETF",
    fundHouse: "NSE ETF",
    expenseRatio: 0.12,
    aumCr: 22000,
    trackingError: 0.14,
    managerTenureYears: 10,
    downsideCaptureRatio: 97
  },
  {
    id: "etf-bankbees",
    provider: "yahoo",
    category: "equity",
    marketSymbol: "BANKBEES.NS",
    benchmarkSymbol: "^NSEBANK",
    nameHint: "BANKBEES ETF",
    fundHouse: "NSE ETF",
    expenseRatio: 0.16,
    aumCr: 9500,
    trackingError: 0.2,
    managerTenureYears: 9,
    downsideCaptureRatio: 102
  },
  {
    id: "etf-itbees",
    provider: "yahoo",
    category: "equity",
    marketSymbol: "ITBEES.NS",
    benchmarkSymbol: "^CNXIT",
    nameHint: "ITBEES ETF",
    fundHouse: "NSE ETF",
    expenseRatio: 0.18,
    aumCr: 3200,
    trackingError: 0.22,
    managerTenureYears: 7,
    downsideCaptureRatio: 104
  },
  {
    id: "gold-goldbees",
    provider: "yahoo",
    category: "gold",
    marketSymbol: "GOLDBEES.NS",
    benchmarkSymbol: "GOLDBEES.NS",
    nameHint: "GOLDBEES ETF",
    fundHouse: "NSE ETF",
    expenseRatio: 0.45,
    aumCr: 4600,
    trackingError: 0.28,
    managerTenureYears: 8,
    downsideCaptureRatio: 72
  },
  {
    id: "gold-hdfcgold",
    provider: "yahoo",
    category: "gold",
    marketSymbol: "HDFCGOLD.NS",
    benchmarkSymbol: "GOLDBEES.NS",
    nameHint: "HDFC Gold ETF",
    fundHouse: "NSE ETF",
    expenseRatio: 0.55,
    aumCr: 2300,
    trackingError: 0.31,
    managerTenureYears: 6,
    downsideCaptureRatio: 74
  },
  {
    id: "debt-corporate-bond",
    provider: "amfi",
    category: "debt",
    marketSearchTerm: "ICICI Prudential Corporate Bond Fund Direct Growth",
    benchmarkSymbol: "LIQUIDBEES.NS",
    nameHint: "Corporate Bond Fund",
    fundHouse: "AMFI Debt",
    expenseRatio: 0.34,
    aumCr: 7400,
    trackingError: 0.12,
    managerTenureYears: 7,
    downsideCaptureRatio: 34
  },
  {
    id: "debt-short-duration",
    provider: "amfi",
    category: "debt",
    marketSearchTerm: "HDFC Short Term Debt Fund Direct Growth",
    benchmarkSymbol: "LIQUIDBEES.NS",
    nameHint: "Short Duration Debt Fund",
    fundHouse: "AMFI Debt",
    expenseRatio: 0.31,
    aumCr: 8100,
    trackingError: 0.11,
    managerTenureYears: 8,
    downsideCaptureRatio: 29
  },
  {
    id: "debt-banking-psu",
    provider: "amfi",
    category: "debt",
    marketSearchTerm: "SBI Banking and PSU Fund Direct Growth",
    benchmarkSymbol: "LIQUIDBEES.NS",
    nameHint: "Banking and PSU Fund",
    fundHouse: "AMFI Debt",
    expenseRatio: 0.29,
    aumCr: 6200,
    trackingError: 0.1,
    managerTenureYears: 6,
    downsideCaptureRatio: 27
  },
  {
    id: "debt-gilt",
    provider: "amfi",
    category: "debt",
    marketSearchTerm: "ICICI Prudential Gilt Fund Direct Growth",
    benchmarkSymbol: "LIQUIDBEES.NS",
    nameHint: "Gilt Fund",
    fundHouse: "AMFI Debt",
    expenseRatio: 0.38,
    aumCr: 4100,
    trackingError: 0.14,
    managerTenureYears: 6,
    downsideCaptureRatio: 32
  },
  {
    id: "cash-liquid",
    provider: "amfi",
    category: "cash",
    marketSearchTerm: "Aditya Birla Sun Life Money Manager Fund Direct Growth",
    benchmarkSymbol: "LIQUIDBEES.NS",
    nameHint: "Money Market Fund",
    fundHouse: "AMFI Liquid",
    expenseRatio: 0.16,
    aumCr: 9300,
    trackingError: 0.07,
    managerTenureYears: 9,
    downsideCaptureRatio: 12
  },
  {
    id: "cash-ultra-short",
    provider: "amfi",
    category: "cash",
    marketSearchTerm: "SBI Magnum Ultra Short Duration Fund Direct Growth",
    benchmarkSymbol: "LIQUIDBEES.NS",
    nameHint: "Ultra Short Duration Fund",
    fundHouse: "AMFI Liquid",
    expenseRatio: 0.2,
    aumCr: 5400,
    trackingError: 0.08,
    managerTenureYears: 7,
    downsideCaptureRatio: 14
  }
];
